services:

  mongo:
    container_name: flash-sale-backend-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db/flash-sale-system-db
    restart: always

  mongo-express:
    container_name: flash-sale-backend-mongo-express
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
  flash-sale-backend:
    container_name: flash-sale-backend
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - mongo
volumes:
  mongo-data: